# Generated by Django 3.2 on 2021-04-22 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='dates',
        ),
        migrations.AddField(
            model_name='session',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 22, 17, 50, 19, 40722)),
        ),
        migrations.AddField(
            model_name='session',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 22, 17, 50, 19, 39726)),
        ),
        migrations.AlterField(
            model_name='session',
            name='finished_at',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='started_at',
            field=models.TimeField(),
        ),
    ]
