# Generated by Django 3.2 on 2021-04-22 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0002_auto_20210422_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 22, 17, 55, 58, 369643)),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 22, 17, 55, 58, 369643)),
        ),
    ]
