# Generated by Django 3.2 on 2021-04-24 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0004_auto_20210422_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='image',
            field=models.ImageField(blank=True, default='defaulthall.jpg', null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='session',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='ticketpurchase',
            name='session_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
