# Generated by Django 3.2 on 2021-04-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0010_alter_hall_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='image',
            field=models.ImageField(blank=True, default='film.jpg', null=True, upload_to='media'),
        ),
    ]
