# Generated by Django 3.2 on 2021-05-03 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0011_alter_session_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketpurchase',
            name='session_date',
        ),
    ]
